name: unit test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        cgo-enabled: ['0', '1']
    env:
      CGO_ENABLED: ${{ matrix.cgo-enabled }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'
          check-latest: true

      - name: Install wgpu-native
        run: |
          curl -sL https://github.com/gfx-rs/wgpu-native/releases/download/v29.0.1.1/wgpu-linux-x86_64-release.zip -o wgpu-native.zip
          unzip -o wgpu-native.zip
          sudo cp libwgpu_native.so /usr/lib/
          sudo ldconfig

      - name: Run coverage tests without CGO
        if: matrix.cgo-enabled == '0'
        run: go test -tags rust -cover ./...

      - name: Run race and coverage tests with CGO
        if: matrix.cgo-enabled == '1'
        run: go test -tags rust -race -cover ./...

  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'
          check-latest: true

      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v23
        with:
          globs: '**/*.md'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          args: ./...
